spring:
  application:
    name: hystrix-service1
server:
  port: 8022
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8011/eureka
    register-with-eureka: true
    fetch-registry: true
