spring:
  application:
    name: hystrix-service1
  cloud:
    config:
      allow-override: true
      override-none: false
      #override-system-properties: false
server:
  port: 8022
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8011/eureka
    register-with-eureka: false
    fetch-registry: true
